#!/usr/bin/php 
<?php 
# Usage: moosh password-reset username [password]
# Summary: Sets a password for a particular user
# Help: Sets a users password. Great for a locked out admin account!
# TODO If you don't specify a password a random one will be created for you and chown to stdout
# TODO If you are lazy you can type the first few chars of a moodle login and it will auto complete for you.

require 'moosh.php';

if (count($argv) < 2){
    print "usage: moosh password-reset username [password]\n";
    exit;
}

$moodle = find_config();
if (!$moodle){
    print "Error: You are not in the context of a moodle install\n";
    exit;
}

define('CLI_SCRIPT', true);
include $moodle.'/config.php';
#require_once($CFG->libdir.'/clilib.php');


# Provide moosh completions
if ($argv[1] == '--complete'){

    $user = count($argv) < 3 ? '' : $argv[2];

    $users = $DB->get_records_sql("SELECT u.username FROM $CFG->prefix"."user u WHERE u.username LIKE ? LIMIT 10", array($user.'%'));
    foreach ($users as $user){
        print $user->username. "\n";
    }
    exit;
}


$username = $argv[1];
if ( count($argv) < 3 ){
    $password = 'random';
} else {
    $password = $argv[2];
}


if (!$user = $DB->get_record('user', array('auth'=>'manual', 'username'=>$username, 'mnethostid'=>$CFG->mnet_localhost_id))) {
    print "Can not find user '$username'";
}

print "Setting the password for '$username' to '$password'\n";
print "Moodle path is $moodle \n";



