#!/usr/bin/env bash
# Usage: moosh update
# Summary: Pulls the latest version of moosh from GitHub.
set -e

mooshgit() {
  GIT_DIR="$_MOOSH_ROOT/.git" git "$@"
}

echo "Updating Moosh!"

mooshgit fetch
mooshgit reset --hard origin/master
