#!/usr/bin/php 
<?php 
# Usage: moosh password-reset username [password]
# Summary: Sets a password for a particular user
# Help: Sets a users password. Great for a locked out admin account!
# TODO If you don't specify a password a random one will be created for you and chown to stdout
# TODO If you are lazy you can type the first few chars of a moodle login and it will auto complete for you.

require 'moosh.php';

if (count($argv) < 2){
    print "usage: moosh password-reset username [password]\n";
    exit;
}

$moodle = find_config();
if (!$moodle){
    print "Error: You are not in the context of a moodle install\n";
    exit;
}

define('CLI_SCRIPT', true);
include $moodle.'/config.php';
require_once($CFG->libdir.'/clilib.php');


# Provide moosh completions
if ($argv[1] == '--complete'){


    if ( count($argv) < 3 ){
        $user = 'crap';
    } else {
        $user = $argv[2];
    }

    # look for the first ten usernames who match the start of this username 
    print "john\n";
    print "phil2ome\n";
    print "dicko3me\n";
    print "ppcicko3me$user\n";
    print "ppdicko3me$user\n";
    print "ppesome".join('==',$_ENV)."\n";
    exit;
}


$username = $argv[1];
if ( count($argv) < 3 ){
    $password = 'random';
} else {
    $password = $argv[2];
}


if (!$user = $DB->get_record('user', array('auth'=>'manual', 'username'=>$username, 'mnethostid'=>$CFG->mnet_localhost_id))) {
    cli_error("Can not find user '$username'");
}

print "Setting the password for '$username' to '$password'\n";
print "Moodle path is $moodle \n";



