#!/usr/bin/perl
# Usage: moosh restore [dbfile]
# Summary: Restore from a DB file
# Help: This abstracts away which DB you are using

use lib "$ENV{'_MOOSH_ROOT'}/libexec";

if ($#ARGV < 0){
    print <<EOF;
Usage: moosh restore [dbfile]

EOF
    exit;
}
# Prov-ide moo-sh comple-tions
if ($ARGV[1] eq '--complete'){
#    print "test $ARGV[1]";
    print `ls $ARGV[1]`;
    exit 0;
}

use Moosh;
use Cwd;
use File::Basename;

# detect local moodle dir
$local = find_moodle(cwd(),'local', 1);

$local_root = dirname($local);


open CONF, $local;
@conf = <CONF>;
close CONF;

# parse local moodle config
%local = parse_config(join "\n", @conf);


do_local_restore($ARGV[0], %local);


